# Generated by Django 5.1.5 on 2025-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(choices=[('swimming', 'Swimming'), ('gym', 'Gym'), ('bowling', 'Bowling'), ('badminton', 'Badminton'), ('pool', 'Pool'), ('table tennis', 'Table Tennis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], max_length=6),
        ),
    ]
