# Generated by Django 5.1.5 on 2025-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0002_alter_facility_facility_name_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_facility',
            field=models.ManyToManyField(related_name='membership_facilities', to='sportscomplex.facility'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='inactive', max_length=10),
        ),
    ]
