# Generated by Django 5.2.1 on 2025-05-12 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0003_membership_membership_facility_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='availability_type',
            field=models.CharField(choices=[('booking_only', 'Booking Only'), ('membership_only', 'Membership Only'), ('both', 'Both Booking and Membership')], default='both', help_text='Determines if facility is available for booking, membership or both', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payments', to='sportscomplex.payment'),
        ),
        migrations.CreateModel(
            name='PaymentRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_booking_rate', models.PositiveIntegerField(blank=True, help_text='Standard per booking rate for facility bookings', null=True)),
                ('membership_rate', models.PositiveIntegerField(blank=True, help_text='Standard monthly membership rate', null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rates', to='sportscomplex.facility')),
            ],
            options={
                'verbose_name_plural': 'Payment Rates',
            },
        ),
    ]
