# Generated by Django 5.2.1 on 2025-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0004_facility_availability_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alleys_booked',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_mixed_gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
