# Generated by Django 5.2.1 on 2025-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0005_booking_alleys_booked_booking_is_mixed_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('alumni', 'Alumni'), ('resident', 'Resident'), ('nstp resident pakistani', 'NSTP Resident Pakistani'), ('nstp resident foreign', 'NSTP Resident Foreign')], help_text='User type this rate applies to', max_length=30, unique=True)),
                ('swimming_rate', models.PositiveIntegerField(default=1000, help_text='Monthly rate for swimming pool access')),
                ('gym_rate', models.PositiveIntegerField(default=1000, help_text='Monthly rate for gym access')),
                ('master_card_rate', models.PositiveIntegerField(default=1500, help_text='Monthly rate for combined swimming pool and gym access (Master Card)')),
            ],
            options={
                'verbose_name': 'User Type Rate',
                'verbose_name_plural': 'User Type Rates',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('alumni', 'Alumni'), ('resident', 'Resident'), ('nstp resident pakistani', 'NSTP Resident Pakistani'), ('nstp resident foreign', 'NSTP Resident Foreign')], max_length=35),
        ),
    ]
