# Generated by Django 5.2.1 on 2025-05-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0007_usertyperate_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffacilityassignment',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='stafffacilityassignment',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffFacilityAssignment',
        ),
    ]
