# Generated by Django 5.2.1 on 2025-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0008_remove_stafffacilityassignment_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='capacity',
            field=models.CharField(choices=[('4', 'Bowling Alleys'), ('3', 'Pool Tables'), ('2', 'Table Tennis Tables')], default='4', help_text='Total number of units available for this facility', max_length=2),
        ),
        migrations.AddField(
            model_name='facility',
            name='cooldown_time',
            field=models.CharField(choices=[('B60', '60 Minutes'), ('P60', '60 Minutes'), ('T30', '30 Minutes')], default='B60', help_text='Cooldown time in minutes between bookings', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('staff', 'Staff'), ('faculty', 'Faculty'), ('student', 'Student'), ('alumni', 'Alumni'), ('resident', 'Resident'), ('nstp resident pakistani', 'NSTP Resident Pakistani'), ('nstp resident foreign', 'NSTP Resident Foreign')], max_length=35),
        ),
        migrations.AlterField(
            model_name='usertyperate',
            name='user_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('faculty', 'Faculty'), ('student', 'Student'), ('alumni', 'Alumni'), ('resident', 'Resident'), ('nstp resident pakistani', 'NSTP Resident Pakistani'), ('nstp resident foreign', 'NSTP Resident Foreign')], help_text='User type this rate applies to', max_length=30, unique=True),
        ),
    ]
