# Generated by Django 5.2.1 on 2025-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0009_facility_capacity_facility_cooldown_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='capacity',
            field=models.CharField(choices=[('4', 'Bowling Alleys'), ('3', 'Pool Tables'), ('2', 'Table Tennis Tables')], default='4', help_text='Total number of units available for this facility', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='cooldown_time',
            field=models.CharField(choices=[('B60', '60 Minutes'), ('P60', '60 Minutes'), ('T30', '30 Minutes')], default='B60', help_text='Cooldown time in minutes between bookings', max_length=3, null=True),
        ),
    ]
