# Generated by Django 5.2.1 on 2025-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportscomplex', '0010_alter_facility_capacity_alter_facility_cooldown_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='cooldown_time',
            field=models.CharField(choices=[('B60', 'B60 Minutes'), ('P60', 'P60 Minutes'), ('T30', 'T30 Minutes')], default='B60', help_text='Cooldown time in minutes between bookings', max_length=3, null=True),
        ),
    ]
