# Generated by Django 5.2.1 on 2025-05-13 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportscomplex', '0008_remove_stafffacilityassignment_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('shift', models.CharField(max_length=15)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportscomplex.facility')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='assignment',
            field=models.ManyToManyField(related_name='staff_assignments', through='staff.StaffFacilityAssignment', to='sportscomplex.facility'),
        ),
    ]
